package jogo.resultado;

public enum TipoResultadoAcao {
    PARTIDA_INICIADA,
    PARTIDA_REINICIADA,
    MOVIMENTO_REALIZADO,
    MOVIMENTO_BLOQUEADO,
    CAIXA_COLETADA,
    DINOSSAURO_ENCONTRADO,
    JOGADOR_CURADO,
    JOGADOR_SEM_KIT,
    DEBUG_ALTERNADO,
    VITORIA,
    DERROTA,
    PARTIDA_ENCERRADA,
    SEM_PARTIDA
}
